name: Generate Sitemap

on:
  push:
    branches:
      - main 

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Generate sitemap
        run: python generate_sitemap.py

      - name: Commit and Push Changes to `update-sitemap` Branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git checkout -b update-sitemap-${{ github.run_id }}
          git add sitemap.xml
          git commit -m "Update sitemap.xml" || echo "No changes to commit"
          git push origin update-sitemap-${{ github.run_id }}

      - name: Create Pull Request
        run: |
          gh pr create --base main --head update-sitemap-${{ github.run_id }} --title "Update sitemap.xml" --body "Automatically generated sitemap update."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
